config/routes.rb
Rails.application.routes.draw do

  root to: "users#index"

  devise_for :users, controllers: { 
  	users: "users", 
  	omniauth_callbacks: "omniauth_callbacks", 
  	registration: "users"}

  resources :users do
    get :subregion_options
  end
  resources :events do
  	get :join, 		  on: :member
  	get :unfollow, 	on: :member
  end

  mount Commontator::Engine => '/commontator'
 
end

app/models/event.rb
class Event < ActiveRecord::Base
	
  has_and_belongs_to_many :users

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  acts_as_commontable

  validates :name, length: {maximum: 100, minimum: 5}
  validates :agemin, :agemax, :number, numericality: { greater_than_or_equal_to: 0 }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :twitter, :vkontakte]

  has_and_belongs_to_many :events
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  acts_as_commontator
  
  	def self.from_omniauth(auth)
  		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    	user.email = auth.uid+"@"+auth.provider+".com"
	    	user.password = Devise.friendly_token[0,20]
		    if auth.provider != 'twitter'
		    	user.name = auth.info.first_name
		    	user.surname = auth.info.last_name
		    else
		    	fullname      = auth.info.name.split(' ')
          user.name     = fullname[1]
          user.surname  = fullname[0]
		    end
		    #user.image = auth.info.image # assuming the user model has an image
  		end
	end

	def country_
  		Carmen::Country.coded(country).name
  	end

  	def city_
  		Carmen::Country.coded(country).subregions.coded(city).name
 	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :find_event, only: [:edit, :show, :update, :destroy, :join, :unfollow]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      current_user.events << @event
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
    #action find_event
  end

  def edit
    #action find_event    
  end

  def update
    #action find_event  
    @event.update_attributes(event_params)
    if @event.errors.empty?
      redirect_to event_path(@event)
    else
      render "edit"
    end
  end
  
  def destroy
    #action find_event  
    @event.destroy
    redirect_to user_path(current_user)
  end

  def event_params
    params.require(:event).permit(:name, :date, :time, :description, :gender, :number,
      :agemin, :agemax, :location, :photo, :latitude, :longitude)
  end

  def find_event
    @event = Event.find(params[:id])
  end

  def join
    #action find_event
    if current_user.events.include?(@event)
      redirect_to current_user
    else
      current_user.events << @event
      redirect_to(:back)
    end 
    
  end

  def unfollow
    #action find_event
    if current_user.events.include?(@event)
      current_user.events.delete(@event)
      redirect_to(:back)
    else
      redirect_to (current_user)
    end
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
	
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def vkontakte
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Vkontakte") if is_navigational_format?
    else
      session["devise.vkontakte_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!
	before_action :find_user, only: [:show, :edit, :update, :destroy]

	def index
		@users = User.all 
	end

	def new
		#registrtions controller
		@user = User.new
	end

	def create
		#registrtions controller
		@user = User.new(user_params)
		if @user.save
	      sign_in @user
	      flash[:success] = "URA URA I VSE TAKOE"
	      redirect_to @user
	    else
	      render 'new'
	    end
	end

	def update
		# find_user action
		@user.update_attributes(user_params)
	    if @user.errors.empty?
	    	sign_in(@user, :bypass => true)
	    	redirect_to user_path(@user)
	    else
	    	render "edit"
	    end
	end

	def edit
		# find_user action
	end

	def show
		# find_user action
	end

	def destroy
		@user.destroy
		render "index"
	end

	def subregion_options
    	render partial: 'subregion_select'
 	end

	protected

	def find_user
		begin
	        @user = User.find(params[:id])
	    rescue
	        render file: "#{Rails.root}/public/404.html", layout: false, status: 404
	    end
	end

	def user_params
    	params.require(:user).permit(:name, :surname, :email, :bday, :gender, :phone, :hobby, :about,
    	 :password, :password_confirmation, :avatar, :country, :city)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/commontator/comments/_actions.html.erb
<% # Clients of this partial must supply the following variables:
   # comment
   # user
%>

<% can_edit = comment.can_be_edited_by?(user)
   can_delete = comment.can_be_deleted_by?(user) %>

<% if can_edit %>
  <%= link_to t('commontator.comment.actions.edit'),
              commontator.edit_comment_path(comment),
              :id => "comment_#{comment.id.to_s}_edit_link",
              :class => "comment_edit_link",
              :remote => true %>
<% end %>

&nbsp;

<% if can_delete %>
  <% is_deleted = comment.is_deleted? %>
  <% del_string = is_deleted ? 'undelete' : 'delete' %>
  <%= link_to t("commontator.comment.actions.#{del_string}"),
              commontator.polymorphic_path([del_string, comment]),
              :confirm => (!is_deleted ? t('commontator.comment.actions.confirm_delete') : nil),
              :method => :put,
              :id => "comment_#{comment.id.to_s}_#{del_string}_link",
              :class => "comment_#{del_string}_link",
              :remote => true %>
<% end %>

app/views/commontator/comments/_body.html.erb
<% # Clients of this partial must provide the following variable:
   # comment
%>

<%= simple_format comment.is_deleted? ? \
      t('commontator.comment.status.deleted_by',
        :deleter_name => Commontator.commontator_name(comment.editor)) : \
      comment.body %>

app/views/commontator/comments/_form.html.erb
<% # Clients of this partial must provide the following variables:
   # comment
   #
   # Optionally, they can also supply the following variables:
   per_page ||= nil
   thread ||= nil
   no_remote ||= false
%>

<% config = comment.thread.config %>

<% if comment.errors.any? %>
  <div class="comment_error_explanation">
    <h3><%= t "commontator.comment.errors.#{comment.id.blank? ? 'create' : 'update'}" %></h3>

    <ul>
      <% comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for([commontator, thread, comment],
             :remote => !no_remote) do |f| %>

  <%= hidden_field_tag :per_page, per_page %>
  
  <div class="comment_form_field">
    <%= f.text_area :body, :rows => '7' %>
  </div>
  
  <div class="comment_form_actions">
    <%= f.submit t("commontator.comment.actions.#{comment.id.blank? ? 'create' : 'update'}") %>
    <%= f.submit t('commontator.comment.actions.cancel'), :name => 'cancel' %>
  </div>
  
<% end %>

app/views/commontator/comments/_list.html.erb
<% # Clients of this partial must supply the following variables:
   # comments
   # user
%>

<% comments.each do |comment| %>
  <%= render :partial => 'commontator/comments/show',
             :locals => { :comment => comment,
                          :user => user } %>
<% end %>

app/views/commontator/comments/_show.html.erb
<% # Clients of this partial must supply the following variables:
   # comment
   # user
%>

<% creator = comment.creator
   name = Commontator.commontator_name(creator) || ''
   link = Commontator.commontator_link(creator, main_app) || ''
   avatar = Commontator.commontator_avatar(creator, self) || ''
%>

<div id="comment_<%= comment.id.to_s %>_div" class="comment">
  <div id="comment_<%= comment.id.to_s %>_top_div" class="comment_div">
    <span id="comment_<%= comment.id.to_s %>_commontator_span" class="comment_commontator">
      <%= link.blank? ? name : link_to(name, link) %>
    </span>
    <span id="comment_<%= comment.id.to_s %>_actions_span" class="comment_actions">
      <%= render :partial => 'commontator/comments/actions',
                 :locals => { :comment => comment,
                              :user => user } %>
    </span>
  </div>
  <div id="comment_<%= comment.id.to_s %>_middle_div" class="comment_div">
    <span id="comment_<%= comment.id.to_s %>_avatar_span" class="comment_avatar">
      <%= avatar %>
    </span>
    <span id="comment_<%= comment.id.to_s %>_votes_span" class="comment_votes">
      <%= render :partial => 'commontator/comments/votes',
                 :locals => { :comment => comment,
                              :user => user } %>
    </span>
    <div id="comment_<%= comment.id.to_s %>_body_div" class="comment_body">
      <%= render :partial => 'commontator/comments/body',
                 :locals => { :comment => comment } %>
    </div>
  </div>
  <div id="comment_<%= comment.id.to_s %>_bottom_div" class="comment_div">
    <span id="comment_<%= comment.id.to_s %>_created_timestamp_span" class="comment_timestamp">
      <%= comment.created_timestamp %>
    </span>
    <br/>
    <span id="comment_<%= comment.id.to_s %>_updated_timestamp_span" class="comment_timestamp">
    <% if comment.is_modified? %>
      <%= comment.updated_timestamp %>
    <% end %>
    </span>
  </div>
</div>

app/views/commontator/comments/cancel.js.erb
<% unless @comment.try(:id).blank? %>
  <% @comment.reload %>
  $("#comment_<%= @comment.id.to_s %>_body_div").html("<%= escape_javascript(
    render :partial => 'body', :locals => { :comment => @comment }) %>");
<% end %>

<% unless @new_comment.nil? %>
  $("#thread_<%= @thread.id %>_new_comment_form_div").html("<%= escape_javascript(
    render :partial => 'form',
           :locals => { :comment => @new_comment,
                        :thread => @thread,
                        :per_page => @per_page }) %>");
<% else %>
  $("#thread_<%= @thread.id %>_new_comment_form_div").hide();

  $("#thread_<%= @thread.id %>_new_comment_link_div").fadeIn();
<% end %>

<%= javascript_proc %>

app/views/commontator/comments/create.js.erb
<%= render :partial => 'commontator/threads/show',
           :locals => { :thread => @thread,
                        :user => @user,
                        :page => @thread.new_comment_page(@per_page),
                        :per_page => @per_page } %>

<% unless @new_comment.nil? %>
  $("#thread_<%= @thread.id %>_new_comment_form_div").html("<%= escape_javascript(
    render :partial => 'form',
           :locals => { :comment => @new_comment,
                        :thread => @thread,
                        :per_page => @per_page }) %>");
<% else %>
  $("#thread_<%= @thread.id %>_new_comment_form_div").hide();

  $("#thread_<%= @thread.id %>_new_comment_link_div").fadeIn();
<% end %>

$("#comment_<%= @comment.id.to_s %>_div").hide().fadeIn()[0].scrollIntoView();

<%= javascript_proc %>

app/views/commontator/comments/delete.js.erb
$("#comment_<%= @comment.id.to_s %>_body_div").html("<%= escape_javascript(
  render :partial => 'body', :locals => { :comment => @comment }) %>");

$("#comment_<%= @comment.id.to_s %>_updated_timestamp_span").html("<%= escape_javascript(
  @comment.updated_timestamp) %>");
                                                           
$("#comment_<%= @comment.id.to_s %>_actions_span").html("<%= escape_javascript(
  render :partial => 'actions',
         :locals => { :comment => @comment,
                      :user => @user }) %>");
         
$("#comment_<%= @comment.id %>_votes_span").html("<%= escape_javascript(
  render :partial => 'votes',
         :locals => { :comment => @comment,
                      :user => @user }) %>");

<%= javascript_proc %>

app/views/commontator/comments/edit.js.erb
$("#comment_<%= @comment.id.to_s %>_body_div").html("<%= escape_javascript(
  render :partial => 'form',
         :locals => { :comment => @comment }) %>");
         
<%= javascript_proc %>

app/views/events/index.html.haml
.content
  .sub_header
    All events
  %table.event_list 
    %tr{:align => "center"}
      %th Name:
      %th Gender:
      %th Type:
      %th Description:
      %th
    - @events.each do |e|
      %tr{:align => "center"}
        %td= link_to e.name, event_path(e)
        %td
          = e.gender
          %td
          %td= e.description
          - if current_user.events.include?(e) then
            %td= link_to "unfollow", unfollow_event_path(e), class: "btn btn-add"
          - else
            %td= link_to "join", join_event_path(e), class: "btn btn-add"
    %tr{:align => "center"}
      %td{:colspan => "4"}= link_to "Add new event", new_event_path, class: "btn btn-confirm"

app/views/events/old_index.html.erb
<h1>All events</h1>

<table>
	<tr align="center">
		<td>Name: </td>
		<td>Gender: </td>
		<td>Type: </td>
		<td>Description: </td>
		<td></td>
	</tr>
	<% @events.each do |e| %>
		<tr align="center">
			<td><%= link_to e.name, event_path(e) %></td>
			<td><%= e.gender %>
			<td><%= e.etype %></td>
			<td><%= e.description %></td>
			<% if current_user.events.include?(e) then %>
			<td><%= link_to "unfollow", unfollow_event_path(e) %></td>
			<% else %>
			<td><%= link_to "join", join_event_path(e) %></td>
			<% end %>
		</tr>
	<% end %>
	<tr align="center">
		<td colspan="4"><%= link_to "Add new event", new_event_path %></td>
	</tr>
</table>

app/views/events/old_show.html.erb
<h1><%= @event.name %></h1>

<br><%= if current_user.events.include?(@event) then
		link_to "unfollow", unfollow_event_path(@event)
	else
 		link_to "join", join_event_path(@event)
 	end %><br>

<br><%= image_tag(@event.photo.url(:thumb)) %><br>
<table>
	<tr>
		<td>Date: </td>
		<td><%= @event.date %></td>
	</tr>
	<tr>
		<td>Time: </td>
		<td><%= @event.time %></td>
	</tr>
	<tr>
		<td>Type: </td>
		<td><%= @event.etype %></td>
	</tr>
	<tr>
		<td>Description: </td>
		<td><%= @event.description %></td>
	</tr>
	<tr>
		<td>Gender: </td>
		<td><%= @event.gender %></td>
	</tr>
	<tr>
		<td>Number: </td>
		<td><%= @event.number %></td>
	</tr>
	<tr>
		<td>Age: </td>
		<td><%= @event.agemin %> - <%= @event.agemax %></td>
	</tr>
	<tr>
		<td><%= link_to "Edit", edit_event_path %></td>
		<td><%= link_to "Delete", @event, method: :delete %></td>
	</tr>
</table>

app/views/events/show.html.haml
.content
  .sub_header
    = @event.name
  %br
    = if current_user.events.include?(@event) then                              |
      link_to "unfollow", unfollow_event_path(@event), class: "btn btn-add"     |
      else                                                                      |
      link_to "join", join_event_path(@event), class: "btn btn-add"             |
      end                                                                       |
    %br
      %br
        %br
          %table.event_list{:width => "50%", :display => "inline"}
            %tr
              %th Date:
              %td= @event.date 
            %tr
              %th Time:
              %td= @event.time
            %tr
              %th Type:
              %td
            %tr
              %th Description:
              %td= @event.description
            %tr
              %th Gender:
              %td= @event.gender
            %tr
              %th Number:
              %td= @event.number
            %tr
              %th Age:
              %td
                = @event.agemin
                \- #{@event.agemax}
          = image_tag(@event.photo.url(:thumb))
          %br
          %br
          = link_to "Edit", edit_event_path, class: "btn btn-confirm"
          = link_to "Delete", @event, method: :delete, class: "btn btn-confirm" 
  / Set height and width with CSS
  #googleMap{:style => "height:600px;width:100%;"}
  / Add Google Maps

  :javascript
    var map;
    function initMap() {
      var myCenter = {lat: #{@event.latitude}, lng: #{@event.longitude}};
      map = new google.maps.Map(document.getElementById('googleMap'), {
        center: myCenter,
        zoom: 12
      });

      var marker = new google.maps.Marker({
        position: myCenter,
        map: map,
        title: 'Hello World!'
      });
    }
  %script{:src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyCg3tpHZzNzF1JWKOruUBy3PrOksKDRvII&callback=initMap"}


  = commontator_thread(@event)

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title Mngr
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
	%body
		.row
			.col-md-10
			.col-md-2
				- if user_signed_in?
					Logged in as
					= succeed "." do
						%strong= current_user.email
					%br
					= link_to "Main", root_path, :class => 'navbar-link'
					|
					= link_to "Events", events_path, :class => 'navbar-link'
					|
					= link_to "Edit profile", edit_user_path(current_user), :class => 'navbar-link'
					|
					= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'
					%br
				- else
					= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'
					|
					= link_to "Login", new_user_session_path, :class => 'navbar-link'
					|
					= link_to image_tag('icon-tw16.png'), user_omniauth_authorize_path(:twitter) 
					|
					= link_to image_tag('icon-fb16.png'), user_omniauth_authorize_path(:facebook) 
					|
					= link_to image_tag('icon-vk16.png'), user_omniauth_authorize_path(:vkontakte)
		- if notice
			%p.alert.alert-success= notice
		- if alert
			%p.alert.alert-danger= alert
		.ControlPanel
			= active_link_to "Main", root_path, :active => :exclusive
			- if user_signed_in?
				= active_link_to "Profile", edit_user_path(current_user), :active => :exclusive
				= active_link_to "Events", events_path, :active => :exclusive
			= active_link_to "Peoples", root_path, :active => :exclusive
			= active_link_to "Media", root_path, :active => :exclusive
			= active_link_to "Help", root_path, :active => :exclusive
		= yield

app/views/layouts/old_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mngr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="row">
  <div class="col-md-10"></div>
  <div class="col-md-2">
  <% if user_signed_in? %>

    Logged in as <strong><%= current_user.email %></strong>.	</br>
  	
    <%= link_to "Main", root_path, :class => 'navbar-link' %> |
    <%= link_to "Events", events_path, :class => 'navbar-link' %> |
    <%= link_to "Edit profile", edit_user_path(current_user), :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <br>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> | 
    <%= link_to image_tag('icon-tw16.png'), user_omniauth_authorize_path(:twitter) %> |
    <%= link_to image_tag('icon-fb16.png'), user_omniauth_authorize_path(:facebook) %> |
    <%= link_to image_tag('icon-vk16.png'), user_omniauth_authorize_path(:vkontakte) %>
  <% end %>
  </div>
</div>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/edit.html.haml
.content
  .sub_header
    Edit
  = form_for @user do |f|
    .form-group
      = f.label :name, class: 'col-sm-1 control-label'
      .col-sm-5
        = f.text_field :name, autofocus: true, class: 'form-control'
      %br
    .form-group
      = f.label :surname, class: 'col-sm-1 control-label'
      .col-sm-5
        = f.text_field :surname, class: 'form-control'
      %br
    .form-group
      = f.label :email, class: 'col-sm-1 control-label'
      .col-sm-5
        = f.email_field :email, class: 'form-control'
      %br
    .form-group
      = f.label :birthday, class: 'col-sm-1 control-label'
      .col-sm-5.date-select
        = f.date_select(:bday, start_year: 1940, end_year: Time.now.year)
      %br
    .form-group
      = f.label :gender, class: 'col-sm-1 control-label'
      .col-sm-5
        = radio_button("user", "gender", "Male")
        = label_tag :gender, "Male"
        = radio_button("user", "gender", "Female")
        = label_tag :gender, "Female"
        = radio_button("user", "gender", "NA")
        = label_tag :gender, "Not sure"
      %br
    .form-group
      = f.label :country, class: 'col-sm-1 control-label'
      .col-sm-5
        = f.country_select :country, priority: %w(BY RU UA), prompt: 'Please select a country'
      %br
    .form-group
      = f.label :city, class: 'col-sm-1 control-label'
      .col-sm-5
        = render partial: 'subregion_select', locals: {parent_region: f.object.country}
      %br
    .form-group
      = f.label :phone, class: 'col-sm-1 control-label'
      .col-sm-5
        = telephone_field("user", "phone", class: 'form-control')
      %br
    .form-group
      = f.label :hobby, class: 'col-sm-1 control-label'
      .col-sm-5
        = f.text_area :hobby, class: 'form-control'
      %br
      %br
      %br
    .form-group
      = f.label :about, class: 'col-sm-1 control-label'
      .col-sm-5
        = f.text_area :about, class: 'form-control'
      %br
      %br
      %br
    .form-group
      = f.label :password, class: 'col-sm-1 control-label'
      .col-sm-5
        = f.password_field :password, autocomplete: "off", class: 'form-control'
      %br
    .form-group
      = f.label :avatar, class: 'col-sm-1 control-label'
      .col-sm-5
        = f.file_field :avatar
      %br
    .form-group
      = f.submit "Update", class: "btn btn-confirm"
  %br
  %br
  %br
  = button_to "Cancel my account", registration_path(@user), data: { confirm: "Are you sure?" }, method: :delete, class: "btn"
  = link_to "Back", :back

app/views/users/old_edit.html.erb
    <h2>Edit</h2>

    <%= form_for @user do |f| %>
    
    <div class="form-group">
        <%= f.label :avatar, class: 'col-sm-4 control-label'  %>
        <div class="col-sm-6">
            <%= f.file_field :avatar %>
        </div>
    </div>


    <div class="form-group">
        <%= f.label :name, class: 'col-sm-4 control-label'  %>
        <div class="col-sm-6">
            <%= f.text_field :name, autofocus: true, class: 'form-control'  %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :surname, class: 'col-sm-4 control-label'  %>
        <div class="col-sm-6">
            <%= f.text_field :surname, autofocus: true, class: 'form-control'  %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :email, class: 'col-sm-4 control-label'  %>
        <div class="col-sm-6">
            <%= f.email_field :email, class: 'form-control'  %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :password, class: 'col-sm-4 control-label'  %> 
        <div class="col-sm-6">
            <%= f.password_field :password, autocomplete: "off", class: 'form-control'  %>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-6">
            <%= f.submit "Update", class: "btn btn-primary" %>
        </div>
    </div>

    <% end %>

    <%= button_to "Cancel my account", registration_path(@user), data: { confirm: "Are you sure?" }, method: :delete, class: 'btn btn-default btn-xs' %><%= link_to "Back", :back %>

app/views/users/old_show.html.erb
<br><%= image_tag(@user.avatar.url(:thumb)) %><br>
<%= @user.name %><br>
<%= @user.surname %><br>
<%= @user.email %><br>


<h2>Your events</h2>
<table>
	<tr align="center">
		<td>Name: </td>
		<td>Gender: </td>
		<td>Type: </td>
		<td>Description: </td>
	</tr>
	<% @user.events.each do |e| %>
		<tr align="center">
			<td><%= link_to e.name, event_path(e) %></td>
			<td><%= e.gender %></td>
			<td><%= e.etype %></td>
			<td><%= e.description %></td>
			<td><%= link_to "unfollow", unfollow_event_path(e)%></td>
		</tr>
	<% end %>
</table>

app/views/users/show.html.haml
%br
  = image_tag(@user.avatar.url(:thumb), class: 'img-circle')
.col-sm-1
  Name:
.col-sm-3
  = @user.name
%br
.col-sm-1
  Surname:
.col-sm-3
  = @user.surname
%br
.col-sm-1
  Email:
.col-sm-3
  = @user.email
%br
.col-sm-1
  Birthday:
.col-sm-3
  = @user.bday
%br
.col-sm-1
  Gender:
.col-sm-3
  = @user.gender
%br
.col-sm-1
  Country:
.col-sm-3
  = @user.country_
%br
.col-sm-1
  City:
.col-sm-3
  = @user.city_
%br
.col-sm-1
  Phone:
.col-sm-3
  = @user.phone
%br
.col-sm-1
  Hobby:
.col-sm-3
  = @user.hobby
%br
.col-sm-1
  About:
.col-sm-3
  = @user.about
%br
%h2 Your events
%table
  %tr{:align => "center"}
    %td Name:
    %td Gender:
    %td Type:
    %td Description:
  - @user.events.each do |e|
    %tr{:align => "center"}
      %td= link_to e.name, event_path(e)
      %td= e.gender
      %td= e.etype
      %td= e.description
      %td= link_to "unfollow", unfollow_event_path(e)